<?php include_once "header.phtml"; ?>
<section class="page-form">

    <h2 class="title-inscription">Inscrivez-vous !</h2>

    <form action="#" method="POST" class="form-inscription">

        <fieldset>
            <legend><label for="last-name">Prénom :</label></legend>
            <input type="text" name="lastname" id="last-name" placeholder="Entre ton prénom" required />
        </fieldset>

        <fieldset>
            <legend><label for="pseudo">Pseudo :</label></legend>
            <input type="pseudo" name="pseudo" id="pseudo" placeholder="Entre un pseudo" required />
        </fieldset>

        <fieldset>
            <legend><label for="email">Email :</label></legend>
            <input type="email" name="email" id="email" placeholder="Entre ton email" required />
        </fieldset>

        <fieldset>
            <legend><label for="password">Mot de passe :</label></legend>
            <input type="password" name="password" id="password" placeholder="Entre ton mot de passe" required />
        </fieldset>

        <br>

        <button type="submit" class="button-submit">Envoyez</button>

    </form>

</section>
<?php include_once "footer.phtml"; ?>