<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="#">STEAZIK</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="#">Accueil<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="playlist">Ma playlist</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">À propos de nous</a>
            </li>

        </ul>
        <form class="form-inline mr-auto my-lg-0">
            <input class="form-control mr-sm-2" type="search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Recherchez</button>
        </form>
        <ul class="navbar-nav  mt-2 mt-lg-0">
            <li class="nav-item">
                <a class="nav-link" href="inscription">Inscription</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Connexion</a>
            </li>
        </ul>
    </div>
</nav>