<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" type="image/svg" href="/assets/img/music-player.svg"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Document</title>
</head>
<body>
<header>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <a class="navbar-brand" href="#">STEAZIK</a>
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="#">Accueil<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="playlist">Ma playlist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">À propos de nous</a>
                </li>
            </ul>
            <form class="form-inline mr-auto my-lg-0">
                <input class="form-control mr-sm-2" type="search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Recherchez</button>
            </form>
            <ul class="navbar-nav  mt-2 mt-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="inscription">Inscription</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Connexion</a>
                </li>
            </ul>
        </div>
    </nav>
</header>
<section>
    <ul>
        <li><img src="https://img.audiofanzine.com/images/u/product/normal/diginoiz-big-room-midi-king-250514.jpg" alt=""></li>
        <li><img src="https://f4.bcbits.com/img/a0903864079_10.jpg" alt=""></li>
        <li><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKMEeqxr6bq7RV2nxvDcYn5FPs6SASdX_B1lyrnOG3jd5yHHuYZw&s" alt=""></li>
        <li><img src="https://i.scdn.co/image/8c212ce1f029993c820a1f2a173a1aa336fdee4b" alt=""></li>
        <li><img src="https://geo-static.traxsource.com/files/images/5eb71fbcedbe2686a99b3d72dff26c14.jpg" alt=""></li>
        <li><img src="https://img.youtube.com/vi/3NqcQLIVfZo/hqdefault.jpg" alt=""></li>
        <li><img src="http://img.mp3rally.com/imager/w_500/h_/4fd6c128ac4393db6e68304fc20e652f.jpg" alt=""></li>







    </ul>
</section>
</body>
</html>