<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" type="image/svg" href="/assets/img/music-player.svg"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Document</title>
</head>
<body>
<header>
    <?php include_once "navigation.phtml"; ?>
</header>
<section>
    <ul>
        <li><img src="https://img.audiofanzine.com/images/u/product/normal/diginoiz-big-room-midi-king-250514.jpg" alt=""></li>
        Big Room Vol.1
        <li><img src="https://f4.bcbits.com/img/a0903864079_10.jpg" alt=""></li>
        Big Room Vol.2
        <li><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKMEeqxr6bq7RV2nxvDcYn5FPs6SASdX_B1lyrnOG3jd5yHHuYZw&s" alt=""></li>
        Big Room Vol.3
        <li><img src="https://i.scdn.co/image/8c212ce1f029993c820a1f2a173a1aa336fdee4b" alt=""></li>
        Big Room Vol.4
        <li><img src="https://geo-static.traxsource.com/files/images/5eb71fbcedbe2686a99b3d72dff26c14.jpg" alt=""></li>
        Big Room Vol.5
        <li><img src="https://img.youtube.com/vi/3NqcQLIVfZo/hqdefault.jpg" alt=""></li>
        Big Room Vol.6
        <li><img src="http://img.mp3rally.com/imager/w_500/h_/4fd6c128ac4393db6e68304fc20e652f.jpg" alt=""></li>
        Big Room Vol.7







    </ul>
</section>
</body>
</html>