<?php include_once "header.phtml"; ?>
<section>
    <ul>
        <li><img src="https://img.audiofanzine.com/images/u/product/normal/diginoiz-big-room-midi-king-250514.jpg" alt=""></li>
        <h3>Big Room Vol.1</h3>
        <li><img src="https://f4.bcbits.com/img/a0903864079_10.jpg" alt=""></li>
        <h3>Big Room Vol.2</h3>
        <li><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKMEeqxr6bq7RV2nxvDcYn5FPs6SASdX_B1lyrnOG3jd5yHHuYZw&s" alt=""></li>
        <h3>Big Room Vol.3</h3>
        <li><img src="https://i.scdn.co/image/8c212ce1f029993c820a1f2a173a1aa336fdee4b" alt=""></li>
        <h3>Big Room Vol.4</h3>
        <li><img src="https://geo-static.traxsource.com/files/images/5eb71fbcedbe2686a99b3d72dff26c14.jpg" alt=""></li>
        <h3>Big Room Vol.5</h3>
        <li><img src="https://img.youtube.com/vi/3NqcQLIVfZo/hqdefault.jpg" alt=""></li>
        <h3>Big Room Vol.6</h3>
        <li><img src="http://img.mp3rally.com/imager/w_500/h_/4fd6c128ac4393db6e68304fc20e652f.jpg" alt=""></li>
        <h3>Big Room Vol.7</h3>







    </ul>
</section>
<?php include_once "footer.phtml"; ?>